version: '1.0'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=databaseteam
      - POSTGRES_PASSWORD=databaseteam123
      - POSTGRES_DB=database_management
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U databaseteam -d database_management" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=databaseteam@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=databaseteam123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      postgres:
          condition: service_healthy

  clickhouse_db:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    user: "0:0" # Cấp quyền root để Docker Mac không bị lỗi volume
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=database_management
      - CLICKHOUSE_USER=databaseteam
      - CLICKHOUSE_PASSWORD=databaseteam123
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"
      - "9000:9000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - node.name=es-node01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  airflow-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow_webserver
    depends_on:
      - airflow-db
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY=something_random_and_long
      - PYTHONPATH=/opt/airflow/src
      - _PIP_ADDITIONAL_REQUIREMENTS=psycopg2-binary redis
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW_CONN_MY_POSTGRES_CONN=postgres://airflow:airflow@airflow-db:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Tuan --lastname Cao --role Admin --email databaseteam@gmail.com && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow_scheduler
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY=something_random_and_long
      - PYTHONPATH=/opt/airflow/src
      - _PIP_ADDITIONAL_REQUIREMENTS=psycopg2-binary redis
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW_CONN_MY_POSTGRES_CONN=postgres://airflow:airflow@airflow-db:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    command: scheduler

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#    volumes:
#      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
#    command: >
#      sh -c "rm -f /var/lib/kafka/data/meta.properties && /etc/confluent/docker/run"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#    volumes:
#      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'

  # --- FLINK STACK (Bản ổn định cho Mac) ---
  flink-jobmanager:
    image: flink:1.18.0-scala_2.12-java11
    container_name: flink_jobmanager
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    volumes:
      # Mount folder build để bạn upload file JAR nhanh
      - ./flink/target:/opt/flink/usrlib
      - ./src/database_config.json:/opt/src/database_config.json

  flink-taskmanager:
    image: flink:1.18.0-scala_2.12-java11
    container_name: flink_taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 5
    volumes:
      - ./src/database_config.json:/opt/src/database_config.json

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  es_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  flink_data:
    driver: local
  redis_data:
    driver: local
  ri_data:
    driver: local